# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationlevel',
            name='order',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
