# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_educationlevel_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationLevel',
            new_name='EduLevel',
        ),
        migrations.AlterModelOptions(
            name='edulevel',
            options={'ordering': ['order'], 'verbose_name': 'Nivel educativo', 'verbose_name_plural': 'Niveles educativos'},
        ),
    ]
