# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170430_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edulevel',
            options={'ordering': ['order', 'code'], 'verbose_name': 'Nivel educativo', 'verbose_name_plural': 'Niveles educativos'},
        ),
        migrations.AddField(
            model_name='edulevel',
            name='cost',
            field=models.FloatField(default=15),
            preserve_default=False,
        ),
    ]
