from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r"^$",
        views.index,
        name="index"
    ),
    url(
        r"^m/(?P<edulevel_code>[\da-zA-Z]+)/$",
        views.student,
        name="student"
    ),
    url(
        r"^m/(?P<edulevel_code>[\da-zA-Z]+)/academic/$",
        views.academic,
        name="academic"
    ),
    url(
        r"^m/(?P<edulevel_code>[\da-zA-Z]+)/academic/"
        "(?P<itinerary_code>[A-Z]+)/$",
        views.itinerary,
        name="itinerary"
    ),
    url(
        r"^m/(?P<edulevel_code>[\da-zA-Z]+)/family/r(?P<responsible_id>\d)/$",
        views.family,
        name="family"
    ),
    url(
        r"^m/(?P<edulevel_code>[\da-zA-Z]+)/extra/$",
        views.extra,
        name="extra"
    ),
    url(
        r"^m/(?P<edulevel_code>[\da-zA-Z]+)/form/$",
        views.form,
        name="form"
    ),
    url(
        r"^m/(?P<edulevel_code>[\da-zA-Z]+)/auth/pick/$",
        views.auth_pick,
        name="auth_pick"
    ),
    url(
        r"^m/(?P<edulevel_code>[\da-zA-Z]+)/auth/exit/$",
        views.auth_exit,
        name="auth_exit"
    ),
    url(
        r"^m/(?P<edulevel_code>[\da-zA-Z]+)/summary/$",
        views.summary,
        name="summary"
    ),
    url(
        r"^condiciones/$",
        views.conditions,
        name="condiciones"
    ),
    url(
        r"^conditions/$",
        views.conditions,
        name="conditions"
    ),
    url(
        r"^change_edulevel/(?P<edulevel_code>[\da-zA-Z]+)/$",
        views.change_edulevel,
        name="change_edulevel"
    ),
]
