STUDENT_DATA = {
    "name": "John",
    "surname": "Test1 Test2",
    "nif": "12345678Y",
    "nie": "",
    "passport": "",
    "gender": "M",
    "home_phone": "",
    "mobile_phone": "555555555",
    "email": "test@test.com",
    "birth_date": "1/6/1975",
    "birth_country": "Spain",
    "birth_province": "Testing",
    "birth_town": "Hometown",
    "nationality": "Spanish",
    "social_security_number": "",
    "address": "Street Chrome, 10",
    "zipcode": "54321",
    "hometown": "Hometown",
    "lastyear_institution": "Google",
    "lastyear_studies": "Computing"
}
